# Shiny Server entry point for bskyconf
# This file is auto-generated by bskyconf::setup_conference().
# Place this directory on your Shiny Server to deploy the app.

config <- bskyconf::read_conference_config("_bskyconf.yml")

bskyconf::run_conference_app(
  conference_name = config$conference_name,
  data_file = file.path(config$data_dir, "table_posts.Rds"),
  conference_slug = config$conference_slug,
  about_text = config$about_text,
  update_text = config$update_text
)
