# Cron job script for updating conference posts
# Auto-generated by bskyconf::setup_conference().
#
# Usage:
#   Rscript /path/to/your/conference/update_posts.R
#
# Crontab example (run every 30 minutes):
#   */30 * * * * /usr/bin/Rscript /path/to/your/conference/update_posts.R >> /var/log/bskyconf.log 2>&1

# Resolve paths relative to this script's location
script_dir <- tryCatch(
  dirname(sys.frame(1)$ofile),
  error = function(e) getwd()
)

config <- bskyconf::read_conference_config(
  file.path(script_dir, "_bskyconf.yml")
)

bskyconf::update_conference_posts(
  hashtags              = config$hashtags,
  data_dir              = file.path(script_dir, config$data_dir),
  posts_per_hashtag     = config$posts_per_hashtag,
  min_date              = if (!is.null(config$min_date)) as.Date(config$min_date),
  exclude_accounts      = config$exclude_accounts,
  exclude_accounts_regex = config$exclude_accounts_regex
)
